"""Remove build-machine traces from the disposable distribution, before release."""
from pathlib import Path
import json
import re
import shutil


def sanitize(bundle: Path) -> None:
    bundle = bundle.resolve(strict=True)
    expected = Path(__file__).resolve().parent / 'dist' / 'WeeklyReport'
    if bundle != expected.resolve():
        raise ValueError('Only windows/dist/WeeklyReport may be sanitized')
    tex = bundle / 'tex'
    notice_manifest = tex / 'tlpkg/wr-licenses/manifest.json'
    legal_files = set(json.loads(notice_manifest.read_text(encoding='utf-8'))['files']) if notice_manifest.is_file() else set()
    removed = 0
    # TeX recreates logs and font caches locally. Never ship developer caches.
    for path in tex.rglob('*'):
        if not path.is_file():
            continue
        relative = path.relative_to(tex).as_posix()
        if relative in legal_files or relative.startswith('tlpkg/wr-licenses/'):
            continue
        unused_format = (path.suffix == '.fmt' and
                         relative.startswith('texmf-var/web2c/') and
                         not relative.startswith('texmf-var/web2c/xetex/'))
        if path.suffix == '.log' or relative.startswith('texmf-var/fonts/cache/') or unused_format:
            if not path.resolve().is_relative_to(bundle):
                raise ValueError('Unexpected link outside distribution')
            path.unlink()
            removed += 1
    for path in (tex / 'texmf-var/fonts/map').rglob('*.map'):
        content = path.read_text(encoding='utf-8')
        content = re.sub(r'(?im)^%.*(?:[a-z]:[/\\]|/home/|/Users/).*$','% Generated by updmap.', content)
        path.write_text(content, encoding='utf-8')
    for relative in (
        'texmf-dist/web2c/updmap.cfg', 'texmf-dist/web2c/fmtutil.cnf',
        'texmf-var/tex/generic/config/language.dat',
        'texmf-var/tex/generic/config/language.dat.lua',
        'texmf-var/tex/generic/config/language.def',
    ):
        path = tex / relative
        if path.exists():
            content = path.read_text(encoding='utf-8')
            content = re.sub(r'(?m)^([#%]|--) Generated by .*$',
                             r'\1 Generated by TeX Live package manager.', content)
            path.write_text(content, encoding='utf-8')
    config = tex / 'texmf-var/fonts/conf/fonts.conf'
    if config.exists():
        content = config.read_text(encoding='utf-8')
        content = re.sub(r'<dir>[^<]*[/\\]texmf-dist[/\\]fonts[/\\](opentype|truetype)</dir>',
                         r'<dir prefix="relative">../../../texmf-dist/fonts/\1</dir>', content)
        config.write_text(content, encoding='utf-8')
    if tex.is_dir():
        shutil.copyfile(Path(__file__).with_name('TeX-NOTICE.txt'), tex / 'README.WeeklyReport.txt')
    print(f'Removed {removed} generated logs/cache files; made TeX configuration portable.')


if __name__ == '__main__':
    sanitize(Path(__file__).resolve().parent / 'dist' / 'WeeklyReport')
